# Site settings
title: Game Developer
email: prismaticnetwork12@gmail.com
description: > # keep this and put description below
  Gameplay developer
url: "https://yourdomain.com" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/gabriel-nunes1/"
github_username: GabrielNunes12
twitter_username: obilas_dev
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
